$title testing communication with GAMS
* This script mimicks what happens in a REMIND run folder when calling this interface,
* replicating the behavior of the 'openscm' realization of REMINDs 15_climate module.
* It defines dummy values for the temperature and forcing variables to simulate a postsolve,
* runs the interface using the defined paths, updates the variables and shows the new values.
* A scm_output.csv file should also appear with the full MAGICC output.

* It needs only the example_temp_data.gms for test initializing temperatures and the 
* expected files from a REMIND run:
* cfg.txt   * for getting configuration values, just $RUNNAME at the time
* magicc/REMIND_$RUNNAME.SCEN   * the emissions scenario generated by REMINDs core/magicc.gms


* Paths, these are now defined in default.cfg
$setGlobal c15_pythonpath "/p/projects/piam/abrahao/piam-scm-interface/venv_scm/bin/python3"
$setGlobal c15_scminterfacepath "/p/projects/piam/abrahao/piam-scm-interface/run_REMIND.py"

* Define previous values for the GAMS temperature and forcing variables to test overwriting
Sets
    tall            "time index"
            /
            1900*3000
            /
    ;

* This declares 1900-3000 values for pm_globalMeanTemperature, with a weird value of 10 in all years to identify errors in loading
$include "example_temp_data.gms";

* Do the same for p15_forc_magicc, but just for a year
Parameter  p15_forc_magicc(tall) anthropogenic radiative forcing /
1999 10
/;

* There is mention that a = is needed on Execute so that GAMS waits for the execution to finish to carry on, 
* but doesn't seem to be the case here
* https://www.gams.com/mccarlGuide/execute_1.htm

* This is the same as the new code in REMINDs 15_climate/openscm/postsolve.gms
display " SCMInterface: Executing python script:"
display "%c15_pythonpath% %c15_scminterfacepath%"

Execute "%c15_pythonpath% %c15_scminterfacepath%"

* Update values
Execute_Loadpoint 'p15_magicc_temp' pm_globalMeanTemperature = pm_globalMeanTemperature;
Execute_Loadpoint 'p15_forc_magicc'  p15_forc_magicc;

* Show updated values
Display pm_globalMeanTemperature
Display p15_forc_magicc
