name: test-scm
channels: 
   - conda-forge
dependencies:
   - pandas
   - numpy
   - pint-pandas
   - pyam
   - ipykernel
   - jupyter
   - pip
   - pip:
     - gdxcc
     - gdx2py     
     - gdxpds
   #   - "--editable=git+https://github.com/gabriel-abrahao/pymagicc@pik-compatible#egg=pymagicc"

